env:
  es2021: true
  node: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  comma-dangle: off
  object-curly-spacing: off
  import/no-unresolved: off
  no-unused-vars: warn
  import/extensions: off
  import/prefer-default-export: off
  no-await-in-loop: off
  no-restricted-syntax: off
